### PR TITLE
Create salvation

### PR DESCRIPTION
**Pull request by KrowK1ng**

### CODE REVIEW

**Comment by KrowK1ng** [comment]
best feature
so true

**Comment by renatbabacaev** [comment]
Well, I'm impressed! Your patch brings new fixes and stability improvements, and also totally overhauls this project! Such an innovative change...

Mmhhh... well, unfortunately, your pull request will not be accepted, in fact, it wasn't... due the fact that here are the codes for classroom tests, and there is no need in improvements.

**Comment by renatbabacaev** [comment]
:p

**Comment by renatbabacaev** [comment]
Nvm... your pull request is accepted ✔️

**Pull request merged**
